# Generated by Django 3.2.12 on 2024-01-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_remove_snippet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='highlighted',
        ),
    ]
